### PR TITLE
App icon artwork

### PR DESCRIPTION
**Pull request by mezpahlan**
Artwork minus the SVG that is now lost forever :(

### CODE REVIEW

**Comment by mezpahlan** [comment]
Yes! I have recovered the SVG! Github is amazing!

**Comment by davidamey** [comment]
I was going to say:

https://github.com/mezpahlan/coffeeround-android/blob/8fac6e386c06dfce168ab85fb75ec6a6461d5769/coffee-round.svg

**Comment by davidamey** [comment]
Want to do another pull with it or add it into this one?

**Comment by mezpahlan** [comment]
Should already be added to this PR. As the second commit.

**Pull request merged**
